name: Move to In Progress
on:
  issue:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "workout tracker"
          column: "In Progress"
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
